welcome:
  message: Hello to ISP Billing Service Point

server:
  servlet:
    context-path: /ISPB
  port: 9092
security.basic.enabled: false
spring:
  thymeleaf:
    reactive:
      max-chunk-size: 8192
    cache: false
  template:
    cache: false
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    #    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      show-sql: true
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    #        default_schema: xxtkg
        default_schema: ISPBILLING
        id.new_generator_mappings: true
        dialect: org.hibernate.dialect.Oracle10gDialect
  datasource:
    platform: oracle
    continue-on-error: true
    driver-class-name: oracle.jdbc.OracleDriver

    #    url: jdbc:oracle:thin:@192.168.0.67:1524:ASCP
    #    username: xxtkg
    #    password: xxtkg
    #    url: jdbc:oracle:thin:@192.168.0.6:1521:PROD
    url: jdbc:oracle:thin:@192.168.0.73:1521:ORCL
    username: ISPBILLING
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password: 123456
    protocol: smtp
  messages:
    always-use-message-format: false # Set whether to always apply the MessageFormat rules, parsing even messages without arguments.
    basename: i18n/messages # Comma-separated list of basenames, each following the ResourceBundle convention.
    cache-seconds: -1 # Loaded resource bundle files cache expiration, in seconds. When set to -1, bundles are cached forever.
    encoding: UTF-8 # Message bundles encoding.
    fallback-to-system-locale: true # Set whether to fall back to the system Locale if no files for a specific Locale have been found.